### ISSUE TITLE
tx-signer: post-Stargate roadmap

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/tmkms#96]
This is a tracking issue for improvements to the `tx-signer` feature which are possible following the [Stargate] upgrade.

- [ ] Protobuf Transaction Support in `stdtx` crate: https://github.com/iqlusioninc/crates/issues/459
- [ ] gRPC Transaction Sources: https://github.com/iqlusioninc/tmkms/issues/97
- [ ] Replace `[[tx_signer.seq_file]]` with on-chain query

This roadmap is still TBD, so please subscribe for updates!

[Stargate]: https://blog.cosmos.network/cosmos-stargate-upgrade-overview-8939475fe673
